### ISSUE TITLE
explicit polymorphism?

### ISSUE THREAD

**Issue by c-cube** [tip-org/benchmarks#6]
It seems to me that it is a bit inconvenient to use implicit polymorphism (à la ML) instead of explicit type parameters, which I think is already present in ad-hoc ways in SMTlib2 (for array types and bitvectors sizes). The `as` construct feels a bit strange `(nil as (list a))` could be simply written `(nil a)`. Of course I understand this is probably too late to change :)

**Comment by nick8325** [comment]
Yes, I think I agree. Originally, we did this for readability - we were planning to have some type inference in expressions so that you wouldn't usually have to use `as`. But maybe the problems don't look too ugly with explicit type application.

It shouldn't be hard to make a tool that converts the old syntax to the new syntax, so I don't see any problems with changing.

**Comment by c-cube** [comment]
About the type inference, you could write `(nil _)` and have the typechecker infer the parameter `_` from the context (à la Hindley Milner). But since this format is designed for automated tools, I think the default syntax should indeed be machine friendly and not require complicated type inference, only checking (which makes explicit polymorphism easy).

**Comment by danr** [comment]
I am neither particularily fond of the `as` construct in smtlib. Explicit type annotations make sense, but it would be annoying to read (and even more so to write).

A sensible middle way could be to allow `(@@ nil a)` for explicit type applications instead of using `as`. (Here I just dreamt up the `@@` syntax, it's not a preference.)

**Comment by c-cube** [comment]
`(@@ nil a)` looks quite unreadable to me (it will have to be written for every application of a polymorphic constructor…), why not just regular application since it's often totally applied?

**Comment by danr** [comment]
I was thinking that you would only need the `@@` (or whatever one would
choose) for the cases that `as` is used for today, namely when all the type
applications cannot be inferred from the arguments. (So not for every
polymorphic constructor.)

**Comment by c-cube** [comment]
I see, something like Coq then, where type parameters are arguments but are usually omitted, except in those particular cases where term arguments are not sufficient to infer. That would make a lot of sense indeed.

**Comment by nick8325** [comment]
Yes, I like Dan's proposal too.

To do my bit of bikeshedding: I think the operator name `@@` is quite ugly. How about using `@` for type application, and another name such as `apply` for lambda application (which currently uses `@`)? Type ascription is much more common than lambda application in the benchmarks (1228 uses of `as` vs. 187 uses of `@`).

**Comment by c-cube** [comment]
Also note that in smtlib, there are things like `( _ BitVec 32)` for parametrizing *symbols* over arguments (in this case, it's the type of bitvectors of length 32). Maybe that would be consistent with type application?

**Comment by nick8325** [comment]
I just committed a patch which removes "as" and adds type application with `_`, like this: `(_ nil a)`.

**Comment by nick8325** [comment]
Closed as the syntax has used explicit polymorphism for ages now.
