### ISSUE TITLE
feature proposal: `lemma`

### ISSUE THREAD

**Issue by c-cube** [tip-org/benchmarks#7]
I don't know where discussions about the TIP format itself should go (some specific mailing list? or the tip-org.github.io page repository?), but in the mean time, I'd like to propose a toplevel statement `(lemma t)` (where `t` is a term of type `Bool`). The statement differs from `(assert t)` in that it must be proved before being used. This seems really useful in the context of inductive theorem proving, which is not cut free. Tools like `quickspec` could then parse a TIP problem and return a new TIP problem that is similar, except it contains additional `lemma` statements containing conjectures.

**Comment by c-cube** [comment]
The statement could be named `(potential-lemma F)` to emphasize that it is not guaranteed to hold, but that it is just a hint for the inductive prover.

**Comment by nick8325** [comment]
Yes, this would be very useful. And of course we can't use `assert` or `assert-not` for that, because they change the logical meaning of the problem, which `potential-lemma` doesn't.

The TIP version of QuickSpec currently uses `assert-not` to label the discovered conjectures, which really is not appropriate...

How about `(hint t)` as a name?

**Comment by nick8325** [comment]
P.S. The mailing list at https://groups.google.com/forum/#!forum/automated-inductive-theorem-proving is probably a good place to discuss these kind of things. It seems all of us had forgotten about it...

**Comment by c-cube** [comment]
"hint" is a step towards the best name, I think, but it doesn't convey the idea that `t` is a property. How about `(hint-assert t)` or something like that?

About the forum, yeah, I  think there is a mailling list designed for such questions — is it  the same? I don't have a google account anymore… But feel free to forward to the mailing list if you want!

**Comment by c-cube** [comment]
@nick8325 I posted it to the mailing list at https://groups.google.com/forum/#!topic/automated-inductive-theorem-proving/AbSdjWk7Hys

**Comment by nick8325** [comment]
I tried adding this a couple of times, but I kept on getting stuck working out what the semantics should be - for example, what should you do when converting to a format that doesn't support lemmas? Maybe a lemma should be a special kind of goal (one which is somehow optional to prove).

The current git version of tip supports annotating formulas (and other things) with SMT-LIB attributes. QuickSpec adds its discovered lemmas as goals, but gives them the `:lemma` attribute, so they look like this: `(prove :lemma ...)`. In other words, you can't use them without proving them (they're not `assert`s), but they're marked as being intermediate lemmas. Maybe that's enough - what do you think?

(I tentatively changed `assert-not` to `prove`, because when there are several conjectures `assert-not` means prove their disjunction, while IMO `prove` ought to mean try proving all of them.)

**Comment by nick8325** [comment]
Closed as the `:lemma` attribute seems to be a reasonable solution to this.
